// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ordenes.Datos;

#nullable disable

namespace Ordenes.Datos.Migraciones
{
    [DbContext(typeof(OrdenesDbContext))]
    [Migration("20260809012400_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ordenes.Modelos.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("EventoId");

                    b.ToTable("eventos_procesados", (string)null);
                });

            modelBuilder.Entity("Ordenes.Modelos.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AsignadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uuid");

                    b.Property<int>("HabitacionNumero")
                        .HasColumnType("integer");

                    b.Property<string>("NotaCierre")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReportadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("ResueltaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResueltoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TecnicoNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TipoFalla")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("HabitacionNumero");

                    b.ToTable("ordenes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
